services:
  - type: web
    name: whisper-transcriber
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: credentials.json
